[package]
name = "grid_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.64"

[dependencies.web-sys]
version = "0.3.64"

features = [
    "console",
    "Window",
    "Document",
    # "DocumentFragment",
    # "Node",
    # "Element",
    "HtmlElement",
    # "HtmlFormElement",
    "HtmlInputElement",
    # "HtmlSlotElement",
    # "HtmlTemplateElement",
    # "CustomElementRegistry",
    # "ShadowRoot",
    # "ShadowRootInit",
    # "ShadowRootMode",
    "SubmitEvent",
    "MutationObserver"
]           

[profile.release]
opt-level = "s"
# opt-level = "z"
lto = true