on:
  release:
    types:
    - created
    
env:
  GITHUB_NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - name: Publish Visual Studio Marketplace
      if: startsWith(github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}