on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - run: npm install
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Configure Git for private repos
      run: |
        git config --global user.name "bstruct"
        git config --global user.email "git@bstruct.com"
        git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
    
    - run: mkdir dist
    - name: Package extension (pre-release)
      run: npx vsce package --pre-release
      env:
        CARGO_NET_GIT_FETCH_WITH_CLI: true
    - name: Publish to Visual Studio Marketplace (pre-release)
      run: npx vsce publish --pre-release --packagePath *.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Publish to Open VSX Registry (pre-release)
      run: npx ovsx publish *.vsix --pre-release
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}