on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: mkdir dist
    - name: Package extension (pre-release)
      run: npx vsce package --pre-release
    - name: Publish to Visual Studio Marketplace (pre-release)
      run: npx vsce publish --pre-release --packagePath *.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Publish to Open VSX Registry (pre-release)
      run: npx ovsx publish *.vsix --pre-release
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}